{ lib }:
{
  username = "loki-sharp";
  userfullname = "LokiSharp";
  useremail = "loki.sharp@gmail.com";
  networking = import ./networking.nix { inherit lib; };
  constants = import ./constants.nix { inherit lib; };
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....F.maB8D8ShDD2y36vomia.$OEGtlDQXRmHTBk.fKflOuz.vbljpOlAUmi3Ue0Xob67";
  # Public Keys that can be used to login to all my PCs and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFpz4P1xXhjZLhgw01BAr4zfzlKzN8+3KPUu1iTBvV22 ed25519-2301"
  ];
}
