{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.routerCore.routing;

  # 一个辅助函数，用于生成 OSPF 接口的配置块
  generateOspfInterfaceConfig = name: value: ''
    interface "${name}" {
      cost ${toString value.cost};
      type broadcast;
      hello ${toString value.helloInterval};
      dead ${toString value.deadInterval};
    };
  '';
in
{
  options.routerCore.routing = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable the BIRD routing daemon.";
    };

    defaultGateway = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "The upstream gateway for the default route (e.g. '1.2.3.4').";
    };

    ospf = lib.mkOption {
      type = lib.types.nullOr (
        lib.types.submodule {
          options = {
            enable = lib.mkOption {
              type = lib.types.bool;
              default = true;
              description = "Enable the OSPFv2 protocol.";
            };
            area = lib.mkOption {
              type = lib.types.str; # OSPF 区域可以是 IP 格式或数字
              default = "0.0.0.0";
              description = "The OSPF area ID.";
            };
            interfaces = lib.mkOption {
              type = lib.types.attrsOf (
                lib.types.submodule {
                  options = {
                    cost = lib.mkOption {
                      type = lib.types.int;
                      default = 10;
                    };
                    helloInterval = lib.mkOption {
                      type = lib.types.int;
                      default = 10;
                    };
                    deadInterval = lib.mkOption {
                      type = lib.types.int;
                      default = 40;
                    };
                  };
                }
              );
              default = { };
              description = "Interfaces on which to run OSPF.";
              # 示例: { "br-lan" = { cost = 10; }; }
            };
          };
        }
      );
      default = null;
      description = "OSPF protocol configuration.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.bird = {
      enable = true;
      config = ''
        # BIRD configuration generated by NixOS

        # === Base Protocols ===
        protocol kernel {
          scan time 20;
          ipv4 {
            import all;
            export all;
          };
        }

        protocol device {
          scan time 10;
        }

        # === Static Default Route ===
        ${
          if cfg.defaultGateway != null then
            ''
              protocol static {
                ipv4;
                route 0.0.0.0/0 via "${cfg.defaultGateway}";
              }
            ''
          else
            ""
        }

        # === OSPF Protocol ===
        ${
          if cfg.ospf != null && cfg.ospf.enable then
            ''
              protocol ospf v2 ospf_v2_core {
                ipv4 {
                  import all;
                  export all;
                };
                area ${cfg.ospf.area} {
                  ${lib.concatStringsSep "\n" (
                    lib.mapAttrsToList generateOspfInterfaceConfig cfg.ospf.interfaces
                  )}
                };
              }
            ''
          else
            ""
        }
      '';
    };
  };
}
